name: Forward changes to mo271.github.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    if: github.repository == 'mo271/klein'

    steps:
      - uses: actions/checkout@v2
        with:
          repository: mo271/mo271.github.io
          token: ${{ secrets.UPDATE_SUBMODULE }}
          submodules: true

      - name: Pull & update the "klein" submodule
        run: |
          git submodule update --init --recursive klein
          git submodule update --remote klein

      - name: Commit
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions - mirror to parent"
          git add --all
          git commit -m "Update klein submodule" || echo "No changes to commit"
          git push
